version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\mholt\caddy

environment:
  GOPATH: c:\gopath

install:
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.8.windows-amd64.zip
  - 7z x go1.8.windows-amd64.zip -y -oC:\ > NUL
  - go version
  - go env
  - go get -t ./...
  - go get github.com/golang/lint/golint
  - go get github.com/gordonklaus/ineffassign
  - set PATH=%GOPATH%\bin;%PATH%

build: off

test_script:
  - go vet ./...
  - go test -race ./...
  - ineffassign .

after_test:
  - golint ./...

deploy: off
